//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: contelem_l
// Function header: contelem_lFunctionMap.h

#ifndef    FUNCTIONMAP_H
#define    FUNCTIONMAP_H

#include    <XSFunctions/Utilities/funcType.h>

class    XSModelFunction;

extern    ModelFunctionMap  XSFunctionMap;

void  createcontelem_lFunctionMap();

extern "C"  {


	xsf77Call    exptau_;
	xsf77Call    contam2func_;
	xsf77Call    contam3func_;
	xsf77Call    contamcof_;
	xsf77Call    contamcofl_;
	xsf77Call    contam4func_;
	xsf77Call    contam5func_;
	xsf77Call    contam53func_;
	xsf77Call    contam54func_;
	xsf77Call    contam542func_;
	xsf77Call    contam32lev_;
	xsf77Call    contam9931func_;
	xsf77Call    mpow_;
	xsf77Call    inv2pow_;
	xsf77Call    exptail_;
	xsf77Call    exptai2_;
	xsf77Call    runpow_;
}


#endif
