//
// Code auto-generated by initpackage (XSPEC12 local model package 
// code generator).  Do not edit
// Package: contelem_l Created :
// Initializer: contelem_l.cxx

#include <XSUser/UserInterface/xstcl.h>

#include  "contelem_lFunctionMap.h"
#include  <XSModelFunction.h>

extern "C" int Contelem_l_Init(Tcl_Interp* tclInterp);
extern "C" int Contelem_l_SafeInit(Tcl_Interp* tclInterp);

int Contelem_l_Init(Tcl_Interp* tclInterp)
{
        return Contelem_l_SafeInit(tclInterp);
}

int Contelem_l_SafeInit(Tcl_Interp* tclInterp)
{

        char PACKAGE[] = "contelem_l";
        char VERSION[] = "1.0";
        Tcl_PkgProvide(tclInterp, PACKAGE, VERSION);
        createcontelem_lFunctionMap();
        XSModelFunction::updateComponentList
              ("/data/legs/rpete/contam/xspec_model/mymodels/model.dat");
        return TCL_OK;

}

