//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: contelem_l
// Function body: contelem_lFunctionMap.cxx

#include    "contelem_lFunctionMap.h"

#include    <XSModelFunction.h>

void 
createcontelem_lFunctionMap()
{


	XSFunctionMap["exptau"]   = new XSCall<xsf77Call>(exptau_);
	XSFunctionMap["contam2"]  = new XSCall<xsf77Call>(contam2func_);
	XSFunctionMap["contam3"]  = new XSCall<xsf77Call>(contam3func_);
	XSFunctionMap["contelem"] = new XSCall<xsf77Call>(contamcof_);
	XSFunctionMap["contelem_L"] = new XSCall<xsf77Call>(contamcofl_);
	XSFunctionMap["contam4"]  = new XSCall<xsf77Call>(contam4func_);
	XSFunctionMap["contam5"]  = new XSCall<xsf77Call>(contam5func_);
	XSFunctionMap["contam53"] = new XSCall<xsf77Call>(contam53func_);
	XSFunctionMap["contam54"] = new XSCall<xsf77Call>(contam54func_);
	XSFunctionMap["contam542"] = new XSCall<xsf77Call>(contam542func_);
	XSFunctionMap["contam32"] = new XSCall<xsf77Call>(contam32lev_);
	XSFunctionMap["contam9931"] = new XSCall<xsf77Call>(contam9931func_);
	XSFunctionMap["mpow"]     = new XSCall<xsf77Call>(mpow_);
	XSFunctionMap["inv2pow"]  = new XSCall<xsf77Call>(inv2pow_);
	XSFunctionMap["exptail"]  = new XSCall<xsf77Call>(exptail_);
	XSFunctionMap["2exptail"] = new XSCall<xsf77Call>(exptai2_);
	XSFunctionMap["runpow"]   = new XSCall<xsf77Call>(runpow_);

}
